name: edgehead
version: 2.0.0
description: A game of fractal stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_collection: ^4.1.0
  built_value: ^6.7.0
  cli_menu: ^0.2.2
  egamebook_builder:
    path: ../egamebook_builder
  meta: 1.1.8  # Pinning meta because of https://github.com/dart-lang/test/issues/1294
  logging: ^0.11.3
  path: ^1.6.2
  quiver: ^2.0.0+1
  slot_machine: ^5.0.1

dev_dependencies:
  args: ^1.5.0
  build_runner: ^1.0.0
  built_value_generator: ^6.7.0
  pedantic: ^1.8.0
  test: ^1.3.0
