name: edgehead
version: 2.0.0
description: A game of fractal stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_collection: ^4.1.0
  built_value: ^7.1.0
  cli_menu: ^0.2.2
  egamebook_builder:
    path: ../egamebook_builder
  meta: 1.2.2
  logging: ^0.11.3
  path: ^1.6.2
  quiver: ^2.0.0+1
  slot_machine: ^5.0.1

dev_dependencies:
  args: ^1.5.0
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  pedantic: ^1.9.2
  test: ^1.15.3
